### ISSUE TITLE
is there anny sqldump for creating tabel?

### ISSUE THREAD

**Issue by Fdiedam** [YukiKume/EqManage#4]

**Comment by Fdiedam** [comment]
is ther anny sql-dump for creating tabel in the database?

**Comment by YukiKume** [comment]
Sorry for the late reply and thanks for having interest in this project. This was a rough high-school project so please understand the (very) rough edges it may have. I should of archived this repository as it is not maintained anymore, and this is also my old account hence I will be inactive for most of the time.

I found a sqldump from 2021, so please try this to see if it works. I did not have intention to open source this so configuration is a little rough, modify the serverconnect.php and login.php file with the database credentials and email credentials. There may be other files you may have to edit. 

Apologies for the mess.
 
[Database.zip](https://github.com/YukiKume/EqManage/files/9332479/Database.zip)
